"""added default role to users

Revision ID: 2e31fc8c19b0
Revises: 6c6f0ebf8dfa
Create Date: 2025-12-25 01:10:03.843012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e31fc8c19b0'
down_revision: Union[str, Sequence[str], None] = '6c6f0ebf8dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
