"""added default values in document

Revision ID: 3f286d4b1259
Revises: 6b2ffcd55fd4
Create Date: 2025-12-30 22:14:09.552309

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '3f286d4b1259'
down_revision: Union[str, Sequence[str], None] = '6b2ffcd55fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
